[package]
name = "new-ordered-float"
version = "1.0.2"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>", "Matt Brubeck <mbrubeck@limpet.net>"]
license = "MIT"
description = "Wrappers for total ordering on floats (fork of ordered-float)"
repository = "https://github.com/mbrubeck/rust-ordered-float"
readme = "README.md"

[lib]
name = "ordered_float"

[dependencies]
num-traits = "0.2"
serde = { version = "1.0", optional = true }
unreachable = "1"

[dev-dependencies]
serde_test = "1.0"
